name = "soulmate"
compatibility_date = "2023-12-01"

vars = { DATABASE_URL='postgresql://soulmate-db_owner:rFfQeg7NJMH9@ep-shy-flower-a7g6cnxp-pooler.ap-southeast-2.aws.neon.tech/soulmate-db?sslmode=require', ENVIRONMENT= 'dev', PARTYKIT_ORIGIN='http://localhost:1999', UPSTASH_URL = 'https://ethical-caribou-41883-us1-vector.upstash.io', UPSTASH_TOKEN = 'ABkFMGV0aGljYWwtY2FyaWJvdS00MTg4My11czFhZG1pbll6Um1PRFppTkRndFpHTmhaUzAwWlRCakxUZzRNMkl0WTJZeVlUQTRaREpqT1dJeA=='}

[env.dev]
vars = { DATABASE_URL='postgresql://soulmate-db_owner:rFfQeg7NJMH9@ep-patient-forest-a74migc5-pooler.ap-southeast-2.aws.neon.tech/soulmate-db?sslmode=require', ENVIRONMENT= 'dev', PARTYKIT_ORIGIN='https://soulmate.lordpachimari.partykit.dev', UPSTASH_URL = 'https://ethical-caribou-41883-us1-vector.upstash.io', UPSTASH_TOKEN = 'ABkFMGV0aGljYWwtY2FyaWJvdS00MTg4My11czFhZG1pbll6Um1PRFppTkRndFpHTmhaUzAwWlRCakxUZzRNMkl0WTJZeVlUQTRaREpqT1dJeA=='}

